name: jLevels
version: '0.1'
main: me.jojjjo147.jLevels.JLevels
api-version: '1.21'
commands:
  level:
    usage: /<command>
    description: See your level
    permission: jlevels.level
  addxp:
    usage: /<command> <player> <xp> [message]
    description: give someone xp
    permission: jlevels.addxp
  givexpbottle:
    usage: /<command> <xp>
    permission: jlevels.addxp
permissions:
  jlevels.level:
    description: Alles to run the /level command
    default: true
  jlevels.addxp:
    description: Give and create XP bottles
    default: op