name: jLevels
version: '1.0-SNAPSHOT'
main: me.jojjjo147.jLevels.JLevels
api-version: '1.21'
commands:
  level:
    usage: /<command>
    description: See your level
    permission: jlevels.level
  addxp:
    usage: /<command> <player> <xp>
    description: give someone xp
    permission: jlevels.addxp
permissions:
  jlevels.level:
    description: Alles to run the /level command
    default: true
  jlevels.addxp:
    description: Give XP to someone
    default: op