# ----------------- Settings -----------------

default_language: en_us # Default language, for when a player's language isn't supported
uniform_language: false # When enabled, The plugin will be in the default_language for all players
xp-formula: "100 + x^1.8" # x is the current level of the player
enable-placeholder-api: true
check-updates: true

rewards:
  monster-kill: 2
  achievement: 10
  player-kill: 5

level-rewards:
  1:
    commands: # Available Placeholders: %player%
      - "give %player% diamond 1"
      - "give %player% dirt 64"
    text:
      - "&3one Dirt"
      - "&e64 Diamonds"

# --------------------------------------------

config-version: 1 # DO NOT CHANGE