name: jLevels
version: '0.3.2'
main: me.jojjjo147.jLevels.JLevels
api-version: '1.21'
softdepend: [PlaceholderAPI]
commands:
  level:
    usage: /<command>
    description: See your level
    permission: jlevels.level
  addxp:
    usage: /<command> <player> <xp> [message]
    description: give someone xp
    permission: jlevels.addxp
  givexpbottle:
    usage: /<command> <xp> <amount>
    permission: jlevels.addxp
  jreload:
    usage: /<command>
    description: reloads the config
    permission: jlevels.reload-config
permissions:
  jlevels.level:
    description: run the /level command
    default: true
  jlevels.addxp:
    description: Give and create XP bottles
    default: op
  jlevels.receive-outdated-warning:
    description: Receive a notification if the plugin is outdated
    default: op
  jlevels.reload-config:
    description: reload the config
    default: op